### ISSUE TITLE
docker-composeでの導入について

### ISSUE THREAD

**Issue by hiroki-tagami** [tsukumijima/KonomiTV#22]
はじめまして、このたびコチラのアプリを使わせてもらおうとdockerで導入を試みましたが
起動するもののWebUIが見えないのでフォローいただけないでしょうか。
そのままでは明らかに動かなかったので以下の点を書き換え(読み替え)ました。

### 環境
OS: Ubuntu20.04 server
Mirakurun: 3.9.0-rc.2(Standby)
 

### 読み替え、書き換え箇所
1. `docker-compose` では バージョン古いと怒られて通らなかったので  `docker compose` でビルド
2.  config.yaml : backend を `Mirakurun` ( 合わせてmirakurun_urlも書き換えました
3.  config.yaml : encoder を `FFmpeg` に （ サーバ機にHWエンコーダがないため
4.  `docker-compose.yaml` の `device` セクションをコメントアウト （上記同様

この状態で ` ⠿ Container KonomiTV  Started ` まで通りますが、HTTPにアクセスすると
` Client sent an HTTP request to an HTTPS server.` と怒られ、 HTTPSアクセスするとchrome が`ERR_SSL_UNRECOGNIZED_NAME_ALERT` を吐きます。

エラー見る限り、SSL周りのなにかが問題なのかなと推測はするのですが、pythonがエラーを吐いているのも気になります。

docker logsの結果を貼っておきます。
```
# docker logs KonomiTV
Success upgrade 0_20210731012247_init.sql
Success upgrade 1_20210810032104_update.sql
Success upgrade 2_20210822031531_update.sql
Success upgrade 3_20210829063149_update.sql
Success upgrade 4_20210903095040_update.sql
Success upgrade 5_20210917083320_update.sql
Success upgrade 6_20220129130828_update.sql
Success upgrade 7_20220426131443_update.sql
Success upgrade 8_20220427154401_update.sql
Success upgrade 9_20220810033000_update.sql
[2022/10/01 02:16:38] INFO:     Started server process [1]
[2022/10/01 02:16:38] INFO:     Waiting for application startup.
[2022/10/01 02:16:38] INFO:     Channels updating...
[2022/10/01 02:16:38] INFO:     Channels update complete. (0.255 sec)
[2022/10/01 02:16:38] INFO:     Programs updating...
[2022/10/01 02:16:40] ERROR:    Traceback (most recent call last):
  File "/code/server/app/models/Program.py", line 399, in updateFromMirakurun
    'middle': ariblib.constants.CONTENT_TYPE[genre['lv1']][1][genre['lv2']].replace('／', '・'),
KeyError: 0

[2022/10/01 02:16:40] INFO:     Programs update complete. (1.069 sec)
[2022/10/01 02:16:40] INFO:     Application startup complete.
[2022/10/01 02:16:40] INFO:     Uvicorn running on http://127.0.0.77:7010 (Press CTRL+C to quit)
[2022/10/01 02:31:40] INFO:     Channels updating...
[2022/10/01 02:31:40] INFO:     Channels update complete. (0.281 sec)
[2022/10/01 02:31:40] INFO:     Programs updating...
[2022/10/01 02:31:41] ERROR:    Traceback (most recent call last):
  File "/code/server/app/models/Program.py", line 399, in updateFromMirakurun
    'middle': ariblib.constants.CONTENT_TYPE[genre['lv1']][1][genre['lv2']].replace('／', '・'),
KeyError: 0

[2022/10/01 02:31:41] INFO:     Programs update complete. (1.382 sec)
```

Mirakurunまわりでエラーが出ているようにも見えたのでコンテナからMirakurunAPIを叩いてみたところ
channelsなどは正常にとれているようです。

**Comment by tsukumijima** [comment]
まず、基本的に master ブランチの利用は自分でなんとかできる方以外にはおすすめしません。
master ブランチには多くの破壊的変更が加わっているほか、導入方法も大幅に変更されています。現時点で導入方法のドキュメントは存在せず、Twitter @TVRemotePlus の過去ツイートで少し述べている程度です。

> docker-compose では バージョン古いと怒られて通らなかったので docker compose でビルド

私は docker-compose v1 でしか動作確認していません。ただ v1 と v2 の間で非互換な部分はあまりないと思うので、v2 でも動くんじゃないかな…？とは思います。

> HTTPSアクセスするとchrome がERR_SSL_UNRECOGNIZED_NAME_ALERT を吐きます。

master ブランチの開発版 KonomiTV は、[極めて特殊な技術](https://github.com/tsukumijima/Akebi) を用いて自己署名証明書をインストールすることなく HTTPS 接続ができるようになっています。
ただし、アクセス時にローカル IP アドレスではなく、`https://192-168-1-11.local.konomi.tv:7000/` のようなアドレスでアクセスする必要があります。
ローカルホスト (127.0.0.1) であれば、`https://my.local.konomi.tv:7000/` / `https://local.local.konomi.tv:7000/` `https://localhost.local.konomi.tv:7000/` のエイリアスも使えます。

> pythonがエラーを吐いているのも気になります。
Mirakurun: 3.9.0-rc.2 とのことですが、私の環境では再現してないのでわからないですね…
おそらくジャンルの数値が未定義になってるんだと思いますが、なぜ Mirakurun の /api/programs からそのような値が降ってくるのかも謎…
`https://(mirakurun_url)/api/programs` のレスポンス内容をいただければこちらで検証してみます。

**Comment by hiroki-tagami** [comment]
ご返信ありがとうございます。


拝見する限り色々私には導入ハードルが高そうなので諦めます。
お手数をおかけして申し訳ございませんでした 🙇🏼

**Comment by tsukumijima** [comment]
ちょうど現在インストーラーやドキュメントを整備しているところなので、もう少しお待ち頂ければと…。
インストーラーの完成後は簡単にインストールできるようになっているはずです。
